version: '3.8'
services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    extra_hosts:
      - "docker.host.internal:host-gateway"
    command:
      # Enable Docker provider for container discovery
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      # Redis provider for JupyterHub proxy
      - --providers.redis.endpoints=docker.host.internal:6379
      - --providers.redis.password=another-secret
      - --providers.redis.username=TOUFIK
      - --providers.redis.rootKey=traefik

      # Define entrypoints - this is crucial for routing
      - --entrypoints.web.address=:8000

      # API and dashboard for debugging
      - --api.insecure=true
      - --api.dashboard=true

      # Logging for debugging
      - --log.level=DEBUG
      - --accesslog=true
    ports:
      - "8022:8000"  # External port 8022 maps to internal port 8000
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  jupyterhub:
    build:
      context: ./jupyterhub
    container_name: jupyterhub
    extra_hosts:
      - "docker.host.internal:host-gateway"
    restart: unless-stopped
    environment:
      - JUPYTERHUB_CRYPT_KEY=your-crypt-key
    depends_on:
      - traefik
    ports:
      - "8081:8081"  # JupyterHub hub port
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
    command: ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
    networks:
      - web

networks:
  web:
    driver: bridge
