version: '3.8'
services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - web

  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.redis.endpoints=redis:6379
      - --entrypoints.http.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.auth_api.address=:8081  # Add the missing entry point
      - --api.insecure=true
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
      - "8081:8081" # JupyterHub API entry point
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - redis
    networks:
      - web

  jupyterhub:
    build:
      context: ./jupyterhub
    container_name: jupyterhub
    restart: unless-stopped
    environment:
      - JUPYTERHUB_CRYPT_KEY=your-crypt-key
    depends_on:
      - redis
      - traefik
    ports:
      - "8000:8000"
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
    command: ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]
    networks:
      - web

  user:
    build:
      context: ./user-image
    container_name: user
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    networks:
      - web

networks:
  web:
    driver: bridge