apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        # Read-only root filesystem
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 999
          allowPrivilegeEscalation: false
        # Redis configuration
        command:
        - redis-server
        - --dir
        - /data
        - --appendonly
        - "yes"
        - --appendfsync
        - everysec
        volumeMounts:
        # Mount PVC for Redis data persistence
        - name: redis-data
          mountPath: /data
        # Mount tmpfs for temporary files Redis needs
        - name: tmp-volume
          mountPath: /tmp
        # Mount tmpfs for Redis runtime files
        - name: redis-tmp
          mountPath: /var/lib/redis
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      # PVC for persistent data
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
      # tmpfs volumes for writable directories Redis needs
      - name: tmp-volume
        emptyDir:
          medium: Memory
      - name: redis-tmp
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
